version: '3.8'

services:
  transcription_service:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=development
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
    depends_on:
      - redis
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"