version: '3.8'

services:
  ai-layer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=5000
      - DEBUG_MODE=false
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_MODEL_NAME=${AZURE_MODEL_NAME}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - TTS_URL=${TTS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - REDIS_URL=redis://redis:6381
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: