version: '3.8'
services:
  llm1_service:
    build:
      context: ./src/llm1_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  llm2_service:
    build:
      context: ./src/llm2_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  stt_service:
    build:
      context: ./src/stt_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  tts_service:
    build:
      context: ./src/tts_service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  orchestrator:
    build:
      context: ./src/orchestrator
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - llm1_service
      - llm2_service
      - stt_service
      - tts_service
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"   # HTTP API
      - "7881:7881"   # WebRTC UDP/TCP
    environment:
      - LIVEKIT_CONFIG_FILE=/etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml 