apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm1-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm1-service
  template:
    metadata:
      labels:
        app: llm1-service
    spec:
      containers:
      - name: llm1-service
        image: llm1_service:latest
        ports:
        - containerPort: 8001
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: llm1-service
spec:
  selector:
    app: llm1-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP 